config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portafolio.home.urls')),
    path('profile/', include('portafolio.myprofile.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portafolio/home/urls.py
from django.urls import path

from . import views


app_name = 'home'

urlpatterns = [
	path('', views.home, name='index'),
]

portafolio/myprofile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
	path(
		'<int:pk>/skills',
		views.SkillsByProfileListView.as_view(),
		name='skills'
	)
]

portafolio/myprofile/models.py
from django.db import models

from .managers import SkillManager


class Profile(models.Model):
	name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	email = models.EmailField(unique=True)
	biography = models.TextField(max_length=255)
	address = models.CharField(max_length=80)
	photo = models.ImageField(upload_to="avatars", blank=True)
	phone_number = models.CharField(max_length=11, blank=True)

	def __str__(self):
		return "{name} {last_name}".format(
			name=self.name,
			last_name=self.last_name
		)


class Skill(models.Model):
	name = models.CharField(max_length=40)
	description = models.TextField()
	photo = models.ImageField(upload_to='skills', blank=True)
	profile = models.ForeignKey(
		Profile,
		related_name='skills',
		on_delete=models.CASCADE
	)
	objects = SkillManager()

	def __str__(self):
		return self.name

portafolio/myprofile/forms.py
import re

from django import forms

from .models import Profile
from .utils import is_empty


class ProfileCreateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = [
			'name',
			'last_name',
			'email',
			'address',
			'biography',
			'photo',
			'phone_number'
		]

	def clean_phone_number(self):
		phone_number = self.cleaned_data['phone_number']

		phone_number_pattern = re.compile(r'\d{4}\d{3}\d{2}\d{2}')

		if not is_empty(phone_number):
			if phone_number_pattern.match(phone_number) is None:
				msj = "Esto no es un número de teléfono vádido {0}.".format(phone_number)
				raise forms.ValidationError(msj)

		return phone_number

portafolio/home/views.py
from django.shortcuts import render

from portafolio.myprofile.models import Profile


def home(request):

	profile = Profile.objects.first()
	context = {
		'profile': profile,
		'skills': profile.skills.by(3)
	}

	return render(request, 'home/index.html', context)

portafolio/myprofile/views.py
from django.views import generic

from .models import Skill


class SkillsByProfileListView(generic.ListView):
	template_name = 'myprofile/skills.html'
	context_object_name = 'skills'

	def get_queryset(self):
		return Skill.objects.filter(profile__pk=self.kwargs['pk'])

portafolio/templates/base.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
	<meta charset="UTF-8">
	<title>{% block title %} Mi Portafolio {% endblock %}</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta name="keywords" content="Desarrollador, portafolio, programador web">
	<meta name="author" content="Engel Pinto">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/font/icon.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>
<body>
	<main>
		<header class="blue white-text">
			<div class="row">
				<div class="col s12 center">
					<h1>Mi Portafolio</h1>
					<p>Presta mucha atención a mi portafolio</p>
				</div>
			</div>
		</header>
		<nav>
			<div class="nav-wrapper blue">
				<a href="#" class="sidenav-trigger" data-target="mobile-sidenav"><i class="material-icons">dashboard</i></a>

				<ul class="hide-on-med-and-down">
					<li>
						<a href="{% url 'home:index' %}">Home 
							<i class="material-icons left">home</i>
						</a>
					</li>
					<li>
						<a href="#">Contacts
							<i class="material-icons left">contacts</i>
						</a>
					</li>
					<li>
						<a href="#">Hobbies 
							<i class="material-icons left">favorite</i>
						</a>
				</li>
				</ul>
			</div>
		</nav>
		<ul class="sidenav" id="mobile-sidenav">
			<ul>
					<li>
						<a href="{% url 'home:index' %}">Home 
							<i class="material-icons left">home</i>
						</a>
					</li>
					<li>
						<a href="#">Contacts
							<i class="material-icons left">contacts</i>
						</a>
					</li>
					<li>
						<a href="#">Hobbies 
							<i class="material-icons left">favorite</i>
						</a>
				</li>
				</ul>
			</div>
		</ul>
		<section id="content">
			<div class="row">
				<div class="col s12 l3 section">
				{% block information %}
					
				{% endblock %}
				</div>
				<div class="col s12 l9">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</section>
	</main>
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'materialize/js/materialize.min.js' %}"></script>
	<script src="{% static 'js/portafolio.js' %}"></script>

</body>
</html>

portafolio/templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ block.super }} | Home {% endblock %}

{% block information %}
	<article class="card-panel section">
		<div class="row">
			<div class="col s12">
				{% if not profile.photo %}
				<img src="{% static 'img/default.jpg'%}" class="circle responsive-img" id="photo" data-name="default" alt="Default">
				{% else %}
				<img src="{{ profile.photo.url }}" class="circle responsive-img" id="photo" data-name="photo" alt="{{ profile.name }}">
				{% endif%}
			</div>
			<div class="col s12">
				<h5>¿Y quién soy?</h5>
				<p id="biography">{{ profile.biography }}</p>
			</div>
		</div>
		<div class="divider"></div>
		<div class="row">
			<div class="col s12">
				<h5> <i class="material-icons left">account_circle</i> Contactos</h5>
				{% if profile.phone_number %}
				<p><i class="material-icons">phone</i> <span id="phone-number">{{ profile.phone_number }}</span></p>
				{% else %}
				<p><i class="material-icons">phone</i> <span id="phone-number"> S/N </span></p>				
				{% endif%}
				<p><i class="material-icons left">email</i> <small>{{ profile.email }}</small></p>
			</div>
		</div>
		<div class="divider"></div>
		<div class="row">
			<div class="col s12">
				<h5>Dirección <i class="material-icons left">place</i> </h5>
				<p id="address">{{ profile.address }}</p>
			</div>
		</div>
	</article>
{% endblock %}

{% block content %}
<article class="card-panel section hoverable">
		<h4 class="blue-text">Mis Habilidades</h4>
		<div class="row">
			{% for skill in skills %}
			<div class="col s12 l6">
				<article class="card">
					<div class="card-image">
					{% if skill.photo %}
					<img src="{{ skill.photo.url }}" class="size-skill-img" data-skill="photo">
					{% else %}
					<img src="{% static 'img/not.jpeg' %}" class="size-skill-img" data-skill="default">
					{% endif %}
					</div>
					<div class="card-content">
						<h4 class="card-title blue-text" data-skill="skill"> {{ skill.name }} </h4>
						<p>{{ skill.description }}</p>
					</div>
				</article>
			</div>
			{% empty %}
			<h5 class="white-text blue lighten-1 chip" data-skill-info="msj">Aún no tiene habilidades agregadas.</h5>
			{% endfor %}
		</div>
	<div class="card-action">
		<a href="{% url 'profile:skills' profile.pk %}" id="link-skills"><i class="material-icons">more</i></a>
	</div>
</article>

<article class="card-panel section hoverable">
	<h4 class="blue-text">Proyectos realizados</h4>	
	<div class="row">
		<div class="col s12 l6">
			<article class="card">
				<div class="card-image">
					<img src="{% static 'img/travis.png' %}" class="size-skill-img">
				</div>
				<div class="card-content">
					<h4 class="card-title blue-text"> Sistema de Control de Asistencias </h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At nam maxime nostrum velit, commodi deleniti consequatur! Dicta minima maxime, aliquid dolore animi, at, eum, laborum eveniet incidunt doloremque deserunt. Quis.</p>
				</div>
			</article>
		</div>
	</div>
	<div class="card-action">
		<a href="#"><i class="material-icons">more</i></a>
	</div>
</article>

<article class="card-panel section hoverable">
	<h4 class="blue-text"> Servicios que ofrezco</h4>
		
	
	<div class="card-action">
		<a href="#"><i class="material-icons">more</i></a>
	</div>
</article>
{% endblock %}

portafolio/templates/myprofile/skills.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ block.super }} | Habilidades {% endblock %}

{% block content %} 
<article class="card-panel section hoverable">
		<h4 class="blue-text">Mis Habilidades</h4>
		<div class="row">
			{% for skill in skills %}
			<div class="col s12 l6">
				<article class="card">
					<div class="card-image">
					{% if skill.photo %}
					<img src="{{ skill.photo.url }}" class="size-skill-img" data-skill="photo">
					{% else %}
					<img src="{% static 'img/not.jpeg' %}" class="size-skill-img" data-skill="default">
					{% endif %}
					</div>
					<div class="card-content">
						<h4 class="card-title blue-text" data-skill="skill"> {{ skill.name }} </h4>
						<p>{{ skill.description }}</p>
					</div>
				</article>
			</div>
			{% empty %}
			<h5 class="white-text blue lighten-1 chip" data-skill-info="msj">Aún no tiene habilidades agregadas.</h5>
			{% endfor %}
		</div>
	<div class="card-action">
		<a href="{% url 'home:index' %}"><i class="material-icons">arrow_back</i></a>
	</div>
</article>
{% endblock %}